### ISSUE TITLE
🐛 GitLab cannot parse project ID from btn-tertiary element

### ISSUE THREAD

**Issue by axi0m** [axi0m/ratatoskr#3]
```Traceback (most recent call last):
  File "ratatoskr.py", line 595, in <module>
    main()
  File "ratatoskr.py", line 543, in main
    projectid = get_gitlab_projectid(htmlsession, repo)
  File "ratatoskr.py", line 121, in get_gitlab_projectid
    project_temp = response.html.find(".btn-tertiary")[0].text```

**Comment by axi0m** [comment]
Replacement code
```python
project_temp = response.html.find("#project_id")
projectid = project_temp[0].attrs['value']
```
